version: '3.1'

services:
  db:
    image: mysql
    container_name: sistema-reservas

    environment:
      MYSQL_DATABASE: 'reservas'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

    ports:
      - '3307:3306'

    volumes:
      - ./mysql:/var/lib/mysql